version: "3"
services:
   api:
      restart: always
      build:
         dockerfile: Dockerfile
         context: ./
      networks:
         - backend
      ports:
         - "3000:3000"
      depends_on:
        - db
   db:
      image: postgres
      restart: always
      environment:
         POSTGRES_PASSWORD: 123
         POSTGRES_USER: test_user
         POSTGRES_DB: test_db
      volumes:
        - ./datadir:/var/lib/postgresql/data
      networks:
        - backend
      ports:
        - "5432:5432"
networks:
   backend:
      driver: bridge
