version: "3"
services:
   api:
      restart: always
      build:
         dockerfile: Dockerfile
         context: ./
      networks:
         - backend
      links:
         - db
      ports:
         - "4000:4000"
      depends_on:
         - db
   db:
      image: postgres
      restart: always
      environment:
         POSTGRES_PASSWORD: example
networks:
   backend:
      driver: bridge
