server:
  host: 0.0.0.0
  port: 3000
  domain: example.com

env:
  environment: local
  logLevel: info
  name: app
  version: 0.0.0

secret: secret

db:
  client: pg
  user: test_user
  password: 123
  host: db
  database: test_db
  port: 5432
